Repository criblio/helm-charts, pull requests merged in 2023-03, with the labels that each got.

#113 Add config.tags to worker chart
  helm-chart-sources/logstream-workergroup/templates/secret.yaml
  helm-chart-sources/logstream-workergroup/tests/secret_test.yaml
  helm-chart-sources/logstream-workergroup/values.yaml
Labels: enhancement

#107 Add events resource to RBAC rules
  helm-chart-sources/edge/values.yaml
Labels: enhancement

#115 Add PR workflow
  .github/workflows/pr.yml
Labels: enhancement, chore

#119 Fix Events apiGroups
  helm-chart-sources/edge/values.yaml
Labels: bug

#114 Use kebabcase to format HPA name correctly
  helm-chart-sources/logstream-workergroup/templates/hpa.yaml
  helm-chart-sources/logstream-workergroup/tests/hpa_test.yaml
Labels: bug

#116 Add default admin role to user
  helm-chart-sources/logstream-leader/templates/secret.yaml
Labels: bug

#117 Allow custom ServiceAccount names
  helm-chart-sources/logstream-workergroup/README.md
  helm-chart-sources/logstream-workergroup/templates/rolebinding.yaml
  helm-chart-sources/logstream-workergroup/templates/serviceaccount.yaml
  helm-chart-sources/logstream-workergroup/tests/serviceaccount_test.yaml
  helm-chart-sources/logstream-workergroup/values.yaml
Labels: enhancement

#120 Make health checks customizable
  helm-chart-sources/logstream-leader/README.md
  helm-chart-sources/logstream-leader/templates/_pod.tpl
  helm-chart-sources/logstream-leader/tests/deployment_test.yaml
  helm-chart-sources/logstream-leader/values.yaml
  helm-chart-sources/logstream-workergroup/README.md
  helm-chart-sources/logstream-workergroup/templates/_pod.tpl
  helm-chart-sources/logstream-workergroup/tests/deployment_test.yaml
  helm-chart-sources/logstream-workergroup/values.yaml
Labels: enhancement

#121 Allow for customizable binding IP/host address.
  helm-chart-sources/logstream-leader/README.md
  helm-chart-sources/logstream-leader/templates/_pod.tpl
  helm-chart-sources/logstream-leader/values.yaml
Labels: enhancement
