Repository criblio/helm-charts, pull requests merged in 2023-04, with the labels that each got.

#122 Update service.yaml
  helm-chart-sources/logstream-workergroup/templates/service.yaml
  helm-chart-sources/logstream-workergroup/tests/service_test.yaml
  helm-chart-sources/logstream-workergroup/values.yaml
Labels: enhancement

#124 Add priorityClassName option to spec
  helm-chart-sources/edge/templates/daemonset.yaml
  helm-chart-sources/edge/tests/daemonset_test.yaml
  helm-chart-sources/edge/values.yaml
Labels: enhancement

#126 Use correct serviceaccount name in _pod.tpl helper.
  helm-chart-sources/logstream-workergroup/templates/_pod.tpl
  helm-chart-sources/logstream-workergroup/tests/serviceaccount_test.yaml
Labels: bug

#132 Fix Helm Unit Tests
  .github/workflows/pr.yml
  helm-chart-sources/edge/templates/common/_extras.tpl
  helm-chart-sources/edge/templates/networking/service.yaml
  helm-chart-sources/edge/tests/daemonset_test.yaml
  helm-chart-sources/edge/tests/extras_test.yaml
  helm-chart-sources/edge/tests/ingress_test.yaml
  helm-chart-sources/edge/tests/rbac_test.yaml
  helm-chart-sources/edge/tests/secret_test.yaml
  helm-chart-sources/edge/tests/service_test.yaml
  helm-chart-sources/edge/tests/values/leader.yaml
Labels: bug, chore

#129 Update `logstream-workergroup` Readme
  helm-chart-sources/logstream-workergroup/README.md
Labels: documentation
